routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListaController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\FormController;
use App\Http\Controllers\DependentesController;
use App\Models\User;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('index',  ['menu' => 'Menu de Opções', 
    'inicio' => 'Início', 
    'listar' => 'Listar Cadastros', 
    'incluir' => 'Incluir Novo']);
   
});

Route::get('/index', function () {
    return view('index', ['menu' => 'Menu de Opções', 
    'inicio' => 'Início', 
    'listar' => 'Listar Cadastros', 
    'incluir' => 'Incluir Novo']);
   
});

Route::get('/recebido', function () {
    return view('recebido',  ['menu' => 'Menu de Opções', 
    'inicio' => 'Início', 
    'listar' => 'Listar Cadastros', 
    'incluir' => 'Incluir Novo']);
   
});

//Route::resource('form', FormController::class);

Route::resource('form', FormController::class);
   
Route::get('/lista',  [ListaController::class, 'render']);

Route::resource('dependentes', DependentesController::class);
   
Route::delete('lista', [ListaController::class, 'destroy']);

Route::delete('lista', [ListaController::class, 'deleteAll']);

Route::get('/recebido', function () {
    return view('recebido',  ['menu' => 'Menu de Opções', 
    'inicio' => 'Início', 
    'listar' => 'Listar Cadastros', 
    'incluir' => 'Incluir Novo']);
   
}); 

resources/views/dependentes.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html"; charset="UTF-8" />

<link type="text/css" rel="stylesheet" href="{{ asset('principal.css') }}"> 

<title>Cadastro de Pessoas</title>
</head>

<body>

<div id="conteudoGeral">

    <div id="topoGeral">
    	<div id="logoTopo" onclick="location.href='index'" style="cursor:pointer;"></div>
    	<div id="dirTopo"></div>
    </div>
    
    <div id="baixoGeral">
    
    	<div id="menuEsq">
            <div id="titMenu">{{$menu}}</div>
            <a href="index">{{$inicio}}</a> 
            <a href="lista">{{$listar}}</a>
            <a href="{{ route ('form.create') }}"> {{$incluir}}</a>
        </div>
        
        <div id="conteudoDir">
        	
            <div id="listaPessoas">
            	<h1>Dependentes</h1>
                
                <div id="infoDep">

                    <div id="fotoCadastro">
                        <img src="/fotoCadastro.png" width="77" height="77" />
                    </div> 
                    
                    <table id="tListaCad" cellpadding="0" cellspacing="0" border="0">
                              

                        <tr>
                            <td class="tituloTab">Nome</td>    
                            <td>Steves Jobs</td>    
                        </tr>              
                        <tr bgcolor="#cddeeb">
                            <td class="tituloTab">Data de Nascimento</td>    
                            <td>25/08/1964</td>    
                        </tr>              
                        <tr>
                            <td class="tituloTab">Email</td>    
                            <td>steve.jobs@apple.com</td>    
                        </tr>              
                    </table>
                    
                    <form id="frmAdicionaDep" method="post" enctype="multipart/form-data" action="{{ route('dependentes.store') }}">
                    {{ csrf_field() }}
                        <div class="agrupa mB mR">
                            <label for="cNomeDep">Nome</label><br />
                            <input type="text" name="cNomeDep" id="cNomeDep" />
                        </div>    
                        <div class="agrupa">
                            <label for="cDataNasc">Data de Nascimento</label><br />
                            <input type="text" name="cDataNasc" id="cDataNasc" />
                          
                        </div>                            
                        <br><br>
                        @if ($errors->any())
                        <div>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
	                    <a href="javascript:frmAdicionaDep.submit();" class="btPadrao">Adicionar</a>
                   
                    </form>
                
                    
                    <table id="tLista" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <th width="60%" class="tL">Nome do Dependente</th>
                            <th width="33%">Data de Nascimento</th>
                            <th></th>
                        </tr>    
                        @foreach ($users as $user)
                        
                            @if ($loop->even)
                            <tr>
                                <td>{{ $user->nome }}</td>
                                <td align="center">{{$user->dtnasc }}</td>
                                <td align="center"><a href="" class="btRemover"></a></td>
                            </tr>
                            @continue
                            @endif
                            @if ($loop->odd)    
                        <tr bgcolor="#cddeeb">
                            <td>{{ $user->nome }}</td>
                            <td align="center">{{ $user->dtnasc }}</td>
                            <td align="center"><a href="" class="btRemover"></a></td>
                        </tr>
                            @endif
                        
                        @endforeach
                    </table>
                    
                    <a href="javascript:;" class="btPadrao mT">Salvar</a>
                </div>
                
            </div>    

        </div> <!-- FIM CONTEUDO DIR -->
    
    </div>

</div>

</body>
</html>

resources/views/form.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html"; charset="UTF-8" />

<link type="text/css" rel="stylesheet" href="{{ asset('principal.css') }}">


<title>Cadastro de Pessoas</title>
</head>

<body>

<div id="conteudoGeral">

    <div id="topoGeral">
    	<div id="logoTopo" onclick="location.href='index'" style="cursor:pointer;"></div>
    	<div id="dirTopo"></div>
    </div>
    
    <div id="baixoGeral">
    
    	<div id="menuEsq">
            <div id="titMenu">{{$menu}}</div>
            <a href="index">{{$inicio}}</a> 
            <a href="lista">{{$listar}}</a>
            <a href="{{ route ('form.create') }}"> {{$incluir}}</a>
        </div>
        
        <div id="conteudoDir">

            <div id="listaPessoas">
            
                <h1>Incluindo um Novo Cadastro</h1>
               
                <form id="formCadastrar" method="post" enctype="multipart/form-data" action="{{ route('form.store') }}">
                    {{ csrf_field() }}
                    <label for="cNome">Nome</label><br />
                    <input id="cNome" name="cNome" value="{{old('cNome')}}" required/><br />

                    <label for="cDataNasc">Data de Nascimento (Formato:dia/mês/ano)</label><br />
                    <input id="cDataNasc" name="cDataNasc" value="{{old('cDataNasc')}}" required /><br />
                    
                    <label for="cEmail">E-Mail</label><br />
                    <input id="cEmail" name="cEmail" type="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" value="{{old('cEmail')}}" required/><br />
                    <label for="cFoto">Foto (somente .jpg - máximo de 200Kb)</label><br />
                    <input id="cFoto" name="cFoto" type="file" accept="image/jpeg" data-max-size="2000"/><br />
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <a href="javascript:formCadastrar.submit()"  class="btPadrao">Salvar</a>
                </form>
               
                
            
            </div>

        </div> <!-- FIM CONTEUDO DIR -->
    
    </div>

</div>

</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html"; charset="UTF-8" />

<link type="text/css" rel="stylesheet" href="{{ asset('/principal.css') }}"> 

<title>Cadastro de Pessoas!</title>
</head>

<body>

<div id="conteudoGeral">

    <div id="topoGeral">
    	<div id="logoTopo" onclick="location.href='index'" style="cursor:pointer;"></div>
    	<div id="dirTopo"></div>
    </div>
    
    <div id="baixoGeral">
    
    	<div id="menuEsq">
            <div id="titMenu">{{$menu}}</div>
            <a href="index">{{$inicio}}</a> 
            <a href="lista">{{$listar}}</a>
            <a href="{{ route ('form.create') }}"> {{$incluir}}</a>
        </div>
        
        <div id="conteudoDir">

            <div id="listaPessoas">
            	<h1>Início</h1>
                Utilize os itens do menu a esquerda para navegar no sistema.
			</div>

        </div> <!-- FIM CONTEUDO DIR -->
    
    </div>

</div>

</body>
</html>

resources/views/lista.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html"; charset="UTF-8" />
<meta name="csrf-token" content="{{ csrf_token() }}" />
<link type="text/css" rel="stylesheet" href="{{ asset('principal.css') }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<title>Cadastro de Pessoas</title>
</head>

<body>

<div id="conteudoGeral">

    <div id="topoGeral">
    	<div id="logoTopo" onclick="location.href='index'" style="cursor:pointer;"></div>
    	<div id="dirTopo"></div>
    </div>
    
    <div id="baixoGeral">
    
    	<div id="menuEsq">
            <div id="titMenu">{{$menu}}</div>
            <a href="index">{{$inicio}}</a> 
            <a href="lista">{{$listar}}</a>
            <a href="{{ route ('form.create') }}"> {{$incluir}}</a>
        </div>
        
        <div id="conteudoDir">

            <div id="listaPessoas">
            	<h1>Cadastros</h1>

				<a href="javascript:;" class="btPadraoExcluir">Excluir</a>
                
                <table id="tLista" cellpadding="0" cellspacing="0" border="0">
                
               

                    <tr>
                        <th width="5%"><input type="checkbox" class="checkbox" id="master"></th>
                        <th width="5%">ID</th>
                        <th width="5%">Foto</th>
                        <th class="tL">Nome</th>
                        <th width="15%">Dt Nasc</th>
                        <th width="25%">Email</th>
                        <th width="7%">Dep</th>
                        <th width="7%">St</th>
                    </tr>
                    @if($users->count())
                    @foreach ($users as $user)
                        @if ($loop->odd)
                    <tr id="tr_{{$user->id}}" bgcolor="#cddeeb">
                    	<td align="center" style="border-left:0;"><input name="chkStatus" type="checkbox" class="sub_chk" data-id="{{$user->id}}" /></td>
                    	<td align="center">{{ $user->id }}</td>
                        <td align="center"><img src="/storage/image/{{$user->foto}}" width="20" height="20" /></td>
                    	<td><a href="{{ route ('form.create') }}" class="linkUser" title="Clique aqui para editar este cadastro." id="nm_">{{ $user->nome }}</a></td>
                    	<td align="center">{{ $dtnasc}}</td>
                        <td align="center">{{ $user->email }}</td>
                        <td align="center">
                        	<a href="{{ route ('dependentes.create', $user->id ) }}" id="{{$user->id}}" class="btAdicionar" title="Adicionar dependentes para este cadastro."></a>
                        </td>
                    	<td align="center">
                        	<!--<a href="javascript:;" class="btVerde" title="Ativar/Desativar este cadastro." id="bol_0"></a>-->
                            <a href="#" class="btVerde" title="Ativar/Desativar este cadastro." name="status" id="bol_{{ $user->id }}" ></a>
                            
                        </td>
                    </tr>
                        @continue
                        @endif
                        @if ($loop->even)
                    <tr id="tr_{{$user->id}}" bgcolor="#f0f0f0">
                    	<td align="center" style="border-left:0;"><input name="chkStatus" type="checkbox" class="sub_chk" data-id="{{$user->id}}"  /></td>
                    	<td align="center">{{ $user->id }}</td>
                        <td align="center"><img src="/storage/image/{{$user->foto}}" width="20" height="20" /></td>
                    	<td><a href="form" class="linkUser" title="Clique aqui para editar este cadastro." id="nm_">{{ $user->nome }}</a></td>
                    	<td align="center">{{ $dtnasc }}</td>
                        <td align="center">{{ $user->email }}</td>
                        <td align="center">
                        
                        	<a href="{{ route ('dependentes.create', $user->id ) }}" class="btAdicionar" title="Adicionar dependentes para este cadastro."></a>
                            
                        </td>
                    	<td align="center">
                        
                            <a href="#" class="btCinza" title="Ativar/Desativar este cadastro." id="{{$user->id}}" name="status"  id="bol_{{ $user->id }}"></a>
                         
                        </td>
                    </tr>
                    
                        @endif
                    @endforeach
                    @endif
                </table>
              
            </div>

            <div id="paginacao">
                <a href="{{ $users->previousPageUrl() }}" class="btSeta1"></a> <div id="pags">1 de {{ $users->count() }}</div> <a href="{{ $users->nextPageUrl() }}" class="btSeta2"></a> 
              
                <select id="paginas">
                <option >1</option>
                <option value="{{ $users->nextPageUrl() }}">2</option>
                <option>3</option>
                <option>4</option>
                </select>

            </div>
          
        </div> <!-- FIM CONTEUDO DIR -->
    
    </div>

</div>
<script type="text/javascript"> 


$( ".btVerde" ).click(function() {
  $( this ).toggleClass( "btCinza" );
});

$( ".btCinza" ).click(function() {
  $( this ).toggleClass( "btVerde" );
  $( this ).removeClass( "btCinza" );
  $( this ).addClass( "btVerde" );
  $( this ).removeClass( "btCinza" );
});


    $(document).ready(function () {


        $('#master').on('click', function(e) {
         if($(this).is(':checked',true))  
         {
            $(".sub_chk").prop('checked', true);  
         } else {  
            $(".sub_chk").prop('checked',false);  
         }  
        });


        $('.btPadraoExcluir').on('click', function(e) {


            var allVals = [];  
            $(".sub_chk:checked").each(function() {  
                allVals.push($(this).attr('data-id'));
            });  


            if(allVals.length <=0)  
            {  
                alert("Please select row.");  
            }  else {  


                var check = confirm("Você tem certeza que quer deletar?");  
                if(check == true){  


                    var join_selected_values = allVals.join(","); 


                    $.ajax({
                        url: $(this).data('url'),
                        type: 'DELETE',
                        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                        data: 'ids='+join_selected_values,
                        success: function (data) {
                            if (data['success']) {
                                $(".sub_chk:checked").each(function() {  
                                    $(this).parents("tr").remove();
                                });
                                alert(data['success']);
                            } else if (data['error']) {
                                alert(data['error']);
                            } else {
                                alert('Whoops Something went wrong!!');
                            }
                        },
                        error: function (data) {
                            alert(data.responseText);
                        }
                    });


                  $.each(allVals, function( index, value ) {
                      $('table tr').filter("[data-row-id='" + value + "']").remove();
                  });
                }  
            }  
        });


        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            onConfirm: function (event, element) {
                element.trigger('confirm');
            }
        });


        $(document).on('confirm', function (e) {
            var ele = e.target;
            e.preventDefault();


            $.ajax({
                url: ele.href,
                type: 'DELETE',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (data) {
                    if (data['success']) {
                        $("#" + data['tr']).slideUp("slow");
                        alert(data['success']);
                    } else if (data['error']) {
                        alert(data['error']);
                    } else {
                        alert('Whoops Something went wrong!!');
                    }
                },
                error: function (data) {
                    alert(data.responseText);
                }
            });


            return false;
        });
    });
</script>   

</script>
</body>
</html>

resources/views/recebido.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html"; charset="UTF-8" />

<link type="text/css" rel="stylesheet" href="{{ asset('/principal.css') }}"> 

<title>Cadastro de Pessoas!</title>
</head>

<body>

<div id="conteudoGeral">

    <div id="topoGeral">
    	<div id="logoTopo" onclick="location.href='index'" style="cursor:pointer;"></div>
    	<div id="dirTopo"></div>
    </div>
    
    <div id="baixoGeral">
    
    	<div id="menuEsq">
            <div id="titMenu">{{$menu}}</div>
            <a href="index">{{$inicio}}</a> 
            <a href="lista">{{$listar}}</a>
            <a href="{{ route ('form.create') }}"> {{$incluir}}</a>
        </div>
        
        <div id="conteudoDir">

            <div id="listaPessoas">
            	<h1>Cadastro realizado com sucesso</h1>
                Recebemos seu cadastro!
			</div>

        </div> <!-- FIM CONTEUDO DIR -->
    
    </div>

</div>

</body>
</html>